- build.rs
Someone reported on IRC that it no longer works. I didn't test the new syntax (we'll see what travis says), but it matches what the docs say: http://doc.crates.io/build-script.html#outputs-of-the-build-script
> Use the new syntax in build.rs

- build.rs
Neither MSYS2 nor [the windows builds](https://github.com/PistonDevelopers/binaries/tree/master/x86_64) use this suffix.
> Remove "-6" suffix

- src/lib.rs
Needed for sub-pixel rendering without color severe color fringes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pistondevelopers/freetype-sys/60)
> Add FT_Library_SetLcdFilter

- src/lib.rs
> Add bindings to `FT_Outline_Translate` and `FT_Outline_Get_CBox`.

- Cargo.toml
- appveyor.yml
- src/lib.rs
Greetings,
The title says it all :) That part of the FreeType2 API is [documented here](https://www.freetype.org/freetype2/docs/reference/ft2-outline_processing.html).  
I made sure to double-check the function signatures.
While I was at it, I allowed myself to make most structs a bit more interesting by making them derive more traits, while being careful not to derive `Copy` and `Clone` for structs that are purposefully marked as "uncopyable".  
This part of the PR may be controversial, but I think that all structs should at least derive `Debug`, because otherwise it's a pain when making higher-level APIs.
Thanks in advance!
> Add Outline API, and make structs derive more traits within reason

- Cargo.toml
- src/lib.rs
I'm trying to use https://github.com/jwilm/alacritty on OpenBSD and the latest version of alacritty needs `FT_Get_Sfnt_Table` (via freetype-rs `TrueTypeOS2Table::from_face`).
Free/Net/OpenBSD support FT_Get_Sfnt_Table in their Freetype2 libraries as explained in the commit message. I've added the corresponding conditional compilation attribute in `src/lib.rs`.
I've tested this on OpenBSD and alacritty compiles and works as expected with this change.
It would be good if we can do a patch level version bump for freetype-sys (like 0.7.1) so we can update the entire dependency chain. I can add a second commit to this PR changing `Cargo.toml` if it's ok.
P.S. I'll open a separate PR for freetype-rs.
> Add FT_Get_Sfnt_Table support for the BSDs

- src/lib.rs
This is a purely mechanical change that follows the pattern used by the
existing definition for the TT_OS2 table.
> Add definition for the TT_Postscript table.

- Cargo.toml
- src/lib.rs
The existing definition was missing some fields after ulUnicodeRange4
and before ulCodePageRange1 and defined fsType as an FT_Short instead of
as an FT_UShort. This would have meant that some fields would not have
been read correctly. Add the missing fields.
A corresponding change to PistonDevelopers/freetype-rs
(PistonDevelopers/freetype-rs#223) adds a test.
> Correctly define TT_OS2 struct.

- src/lib.rs
Those bindings are commonly used to handle `90-synthetic.conf` Fontconfig options.
> Add ftsynth bindings

- build.rs
Avoids excluding EABI target to ensure successful Linux compilation
> Fix: Avoid excluding EABI target

- src/lib.rs
Just in case you'll decide to bump version, this is not a breaking change, so only `patch` should be bumped, since `major` is `0`.
> Add property manipulation bindings.

- build.rs
Hardcode the name of the library folder for cmake to match the other hardcoded reference.
> Hardcode lib name

- Cargo.toml
- build.rs
This is a partial revert of PR https://github.com/PistonDevelopers/freetype-sys/pull/106 which seems to have accidentally dropped support for using pkg-config / dynamically linking with system libfreetype.
Compared to the pkg-config related code that was removed, the only change I made is updating the minimum required version to "24.3.18" in the pkg-config call - which corresponds to freetype2 v2.12.1 (which is what the bundled version was updated to with the last release).
Fixes #108
> Restore pkg-config / dynamic linking support

- src/lib.rs
These were removed in FreeType2 and weren't supposed to be public.
Fixes #74.
> Remove FT_Outline_(New|Done)_Internal.

- src/lib.rs
This is a missing step on supporting rendering fonts as SDFs, intended to be used on `freetype-rs`.
> Add SDF RENDER_MODE constant

- src/lib.rs
FT_Get_Name_Index glyph_name no need to be mutable
https://freetype.org/freetype2/docs/reference/ft2-information_retrieval.html#ft_get_name_index
> fix: FT_Get_Name_Index accept unmutable glyphname

- src/lib.rs
FT_Get_Color_Glyph_Layer is useful in particular for determining whether or not an individual glyph (rather than an entire face) has color layers. Until now it has not been exposed by freetype-sys.
This was introduced in freetype 2.10 according to the docs but certainly is available in the bundled v2.13 release.
> Add FT_Get_Color_Glyph_Layer, introduced in freetype 2.10

- build.rs
pkgconfig `find()` and `probe()` functions will return `Ok()` when building for `-ohos` targets, however there is no prebuilt dynamic or static library to link to in the SDK or on OHOS devices. It's required to build freetype from source instead.
> Skip pkgconfig on OpenHarmony OS

- src/lib.rs
This adds the missing `FT_Load_Sfnt_Table` API and also makes the namse of the `FT_SFNT_*` enum members capitalized so that they match the names of other enums and the FreeType API itself.
`FT_Load_Sfnt_Table` is used by Servo.
> Add `FT_Load_Sfnt_Table` and fix name of `FT_SFNT_*` enum members

- Cargo.toml
- README.md
- build.rs
Previously, `freetype-sys` would first try to find the system FreeType
via pkg-config and then fall back to compiling the vendored version of
FreeType unconditionally.
This change adds a `bundled` feature which allows the users of the crate
to have more control over whether or not the static version of FreeType
is used. If the feature is not passed, FreeType will not be
statically-linked even if it isn't found via pkg-config. This matches
the approach that `harfbuzz-sys` uses as well as `openssl-sys` (via the
`vendored` feature).
> Add a `bundled` Cargo feature

- src/lib.rs
This fixes running clippy against this crate.
> Mark `FT_*` macro functions as unsafe, document.

- Cargo.toml
- src/lib.rs
This is a breaking change since `libc::c_void` is not exactly the same as `std::os::raw::c_void` / `core::ffi::c_void`.
> Remove dependency on `libc`.
